In [14]:
import pandas as pd
import matplotlib.pyplot as plt




top_left = {}

top_left["male"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.122	0.070	0.186
159	0.250	0.166	0.102	0.250
476	0.500	0.231	0.155	0.319
1111	1.000	0.318	0.241	0.405
2381	2.000	0.432	0.336	0.527
4920	4.000	0.602	0.497	0.699
9999	8.000	0.769	0.698	0.835"""

top_left["female"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.173	0.114	0.246
159	0.250	0.223	0.149	0.305
476	0.500	0.332	0.236	0.429
1111	1.000	0.451	0.356	0.554
2381	2.000	0.582	0.479	0.684
4920	4.000	0.704	0.631	0.777
9999	8.000	0.773	0.709	0.833"""

bottom_left = {}

bottom_left["asian"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.100	0.041	0.189
159	0.250	0.128	0.058	0.242
476	0.500	0.210	0.116	0.327
1111	1.000	0.312	0.219	0.422
2381	2.000	0.452	0.350	0.562
4920	4.000	0.625	0.524	0.717
9999	8.000	0.719	0.616	0.807"""

bottom_left["black"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.106	0.059	0.168
159	0.250	0.144	0.086	0.225
476	0.500	0.213	0.133	0.307
1111	1.000	0.297	0.219	0.414
2381	2.000	0.400	0.294	0.526
4920	4.000	0.613	0.465	0.735
9999	8.000	0.767	0.683	0.848"""

bottom_left["white"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.250	0.164	0.345
159	0.250	0.306	0.210	0.421
476	0.500	0.391	0.291	0.500
1111	1.000	0.507	0.405	0.606
2381	2.000	0.633	0.547	0.719
4920	4.000	0.742	0.660	0.826
9999	8.000	0.811	0.743	0.872"""

top_right = {}

top_right["male"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.143	0.059	0.238
159	0.250	0.241	0.154	0.342
476	0.500	0.354	0.262	0.467
1111	1.000	0.489	0.392	0.592
2381	2.000	0.616	0.521	0.700
4920	4.000	0.737	0.652	0.815
9999	8.000	0.866	0.805	0.917"""

top_right["female"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.261	0.161	0.393
159	0.250	0.369	0.280	0.469
476	0.500	0.438	0.346	0.548
1111	1.000	0.572	0.480	0.671
2381	2.000	0.683	0.606	0.768
4920	4.000	0.785	0.724	0.855
9999	8.000	0.868	0.819	0.916"""

bottom_right = {}

bottom_right["asian"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.133	0.046	0.247
159	0.250	0.223	0.124	0.371
476	0.500	0.374	0.259	0.500
1111	1.000	0.497	0.362	0.630
2381	2.000	0.585	0.477	0.685
4920	4.000	0.689	0.561	0.802
9999	8.000	0.818	0.708	0.905"""

bottom_right["black"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.193	0.092	0.315
159	0.250	0.239	0.153	0.372
476	0.500	0.337	0.212	0.507
1111	1.000	0.523	0.389	0.669
2381	2.000	0.666	0.560	0.795
4920	4.000	0.791	0.705	0.874
9999	8.000	0.897	0.841	0.951"""

bottom_right["white"] = """	fps	mean_sens	low_sens	high_sens
0	0.125	0.297	0.123	0.430
159	0.250	0.409	0.315	0.503
476	0.500	0.488	0.383	0.590
1111	1.000	0.576	0.488	0.672
2381	2.000	0.706	0.613	0.788
4920	4.000	0.803	0.740	0.864
9999	8.000	0.898	0.848	0.948"""


def display_error_bar_plots(top_left, top_right, bottom_left, bottom_right):
    def convert_to_dataframe(data):
        data = data.split("\n")
        data = [line.split("\t") for line in data]
        df = pd.DataFrame(data[1:], columns=data[0]).drop(columns=[''])
        return df
    
    def plot_error_bar(ax, df, title, xlabel, ylabel):
        bar_width = 0.1
        index = np.arange(len(fppi_levels))

        for idx, cat in enumerate(means.keys()):
            plt.errorbar(index + cat_increments[cat], means[cat], yerr=errors[cat], fmt='o',label=cat, capsize=5)

        plt.xlabel('False Positives Per Scan')
        plt.ylabel('Sensitivity')
        plt.title(title_template, fontsize=24)
        plt.xticks(index, fppi_levels)
        plt.legend()
        plt.ylim(0.0, 1.0)  # Adjust ylim based on your data range

        plt.grid(True)
        plt.tight_layout()


    top_left = convert_to_dataframe(top_left)
    top_right = convert_to_dataframe(top_right)
    bottom_left = convert_to_dataframe(bottom_left)
    bottom_right = convert_to_dataframe(bottom_right)

    fig, axs = plt.subplots(2, 2, figsize=(15, 15))

     fps mean_sens low_sens high_sens
0  0.125     0.122    0.070     0.186
1  0.250     0.166    0.102     0.250
2  0.500     0.231    0.155     0.319
3  1.000     0.318    0.241     0.405
4  2.000     0.432    0.336     0.527
5  4.000     0.602    0.497     0.699
6  8.000     0.769    0.698     0.835